name: on-push-publish-to-npm
on:
  workflow_dispatch:

jobs:
  publish:
    if: github.repository == 'adobe/uix-sdk'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Ensure public access for @adobe/uix-core
        run: npm access public @adobe/uix-core
        env:
          NPM_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
      - name: Ensure public access for @adobe/uix-guest
        run: npm access public @adobe/uix-guest
        env:
          NPM_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
      - name: Ensure public access for @adobe/uix-host
        run: npm access public @adobe/uix-host
        env:
          NPM_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
      - name: Ensure public access for @adobe/uix-host-react
        run: npm access public @adobe/uix-host-react
        env:
          NPM_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
